baseurl                 = "/"               # Your domain name. Must end with "/"
languageCode            = "en-us"
defaultContentLanguage  = "en"
isMultilingual          = false
title                   = "Atharva's Personal Page"
theme                   = "sam"
# pygmentsStyle           = "monokai"                     # https://help.farbox.com/pygments.html
# pygmentsCodefences      = true
# googleAnalytics         = ""             # Tracking code, eg. "UA-111111111-1"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "favicon.ico"
    homepage            = "home"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = true                          # Allow links to the full size images
    smallPreviewImages   = true                         # Show small images from the subfolder instead of the big versions in the gallery
                                                         # Note: This will only become active if clickablePhotos is also true.
    smallImagesSubfolder = "small/"                      # The subfolder for the small versions of the images under the gallery (with trailing slash)
                                                         # For each image the small version has to have the same filename as the big version.
    footerText          = "i should put a copyright message here i think."

# Metadata
    description         = "Atharva's Blog"            # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "githubprof.png"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/posts"
    text = "posts"

[[params.mainMenu]]
    link = "/resume.pdf"
    text = "résumé"

[[params.mainMenu]]
    link = "/aboutme"
    text = "who dis?"

[taxonomies]
    tag = "tags"
